### Get all comments (default pagination)
GET http://localhost:8080/api/v1/comments

### Get comments with pagination
GET http://localhost:8080/api/v1/comments?page=0&size=5&sort=id,desc

### Create new comment
POST http://localhost:8080/api/v1/comments
Content-Type: application/json

{
  "comment": "I cannot log into my account, it keeps failing.",
  "author": "Yusuf",
  "sourceChannel": "APP_REVIEW"
}

### Create positive comment (should NOT create ticket ideally)
POST http://localhost:8080/api/v1/comments
Content-Type: application/json

{
  "comment": "I liked the app.",
  "author": "User123",
  "sourceChannel": "CHAT_WIDGET"
}

### Create billing issue (should be HIGH priority)
POST http://localhost:8080/api/v1/comments
Content-Type: application/json

{
  "comment": "I was charged twice for my subscription.",
  "author": "CustomerX",
  "sourceChannel": "OTHER"
}

### Get all tickets
GET http://localhost:8080/api/v1/tickets

### Get tickets with pagination
GET http://localhost:8080/api/v1/tickets?page=0&size=5&sort=id,desc

### Get ticket by ID
GET http://localhost:8080/api/v1/tickets/1
