spring.application.name=pulsedesk
ai.model=meta-llama/Llama-3.3-70B-Instruct
ai.huggingface.token=${HF_TOKEN}
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:pulsedesk
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver